version: 8
updates:
- package-ecosystem: " * "
  directory:   "
  /
  "
  schedule:
    interval: daily
  open-pull-requests-limit: [          ]
- package-ecosystem: " * "
  directory: "/src"

  schedule:
    interval: daily
  open-pull-requests-limit: [         ]
 package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit:  [      ]
  ignore: License
